# Site settings
title: Hong Blog
description: 
keywords: 
author: 
baseurl: "/Blog" # the subpath of your site, e.g. /blog/
url: "https://arpeshong.github.io" # the base hostname & protocol for your site
